# Generated by Django 4.2.23 on 2025-09-19 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shoes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('img', models.URLField(blank=True, max_length=500, null=True)),
                ('title', models.CharField(max_length=200)),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cart', models.BooleanField(default=False)),
                ('aosDelay', models.IntegerField(default=0)),
            ],
        ),
    ]
