# Generated by Django 4.2.23 on 2025-09-22 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineMarketApp', '0002_alter_shoes_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoes',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='D:\\Image'),
        ),
    ]
