# Generated by Django 4.2.23 on 2025-09-23 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineMarketApp', '0003_alter_shoes_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoes',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='shoes/'),
        ),
    ]
