# Generated by Django 4.2.23 on 2025-09-30 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineMarketApp', '0006_mens_wear'),
    ]

    operations = [
        migrations.CreateModel(
            name='Electronics',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('img', models.ImageField(blank=True, null=True, upload_to='electronics/')),
                ('title', models.CharField(max_length=200)),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cart', models.BooleanField(default=False)),
                ('aosDelay', models.IntegerField(default=0)),
            ],
        ),
    ]
