# Generated by Django 4.2.23 on 2025-09-30 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineMarketApp', '0009_fashion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('img', models.ImageField(blank=True, null=True, upload_to='hero/')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
