# Generated by Django 4.2.23 on 2025-10-01 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineMarketApp', '0010_hero'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopProducts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('img', models.ImageField(blank=True, null=True, upload_to='top_products/')),
                ('title', models.CharField(max_length=200)),
                ('cart', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
