# Generated by Django 4.2.23 on 2025-11-13 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineMarketApp', '0014_subscription_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
