# Generated by Django 4.2.23 on 2025-11-29 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineMarketApp', '0015_hero_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
