# Generated by Django 4.2.23 on 2025-12-05 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineMarketApp', '0016_delete_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='cost',
            new_name='price',
        ),
    ]
